function amplifier_data = readIntanPerTypeOneChannel(filepath, iduration, istart, nCh, ch)
% readIntanPerType
%
% based on read_Intan_RHD2000_file, edited by Hannah Payne, Aronov lab
%
% Version 3.00, 18 April 2018
%
% Reads Intan Technologies RHD2000 data file generated by evaluation board
% GUI or Intan Recording Controller.
%
% Returns the raw data in matrix form (n sample x n channels)

% Load the file in memory
datatype = 'int16';
filenamestruct = dir(filepath);
dataTypeNBytes = numel(typecast(cast(0, datatype), 'uint8')); % determine number of bytes per sample
nSamp = filenamestruct.bytes/(nCh*dataTypeNBytes);  % Number of samples per channel
mmf = memmapfile(filepath, 'Format', {datatype, [nCh nSamp], 'x'});


        amplifier_data = 0.195*mmf.Data.x(ch,istart:istart+iduration-1);

